-- ============================================================
--  ARSÈNE — схема базы данных для Supabase
--  Как применить: Supabase → раздел "SQL Editor" → New query →
--  вставить ВЕСЬ этот файл → Run. Выполнять один раз.
-- ============================================================

-- ---------- 1. ПРОФИЛИ ПОКУПАТЕЛЕЙ ----------
create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  name       text,
  phone      text,
  role       text not null default 'user',      -- 'user' или 'admin'
  cart       jsonb not null default '[]'::jsonb, -- корзина покупателя
  favorites  jsonb not null default '[]'::jsonb, -- избранное
  created_at timestamptz not null default now()
);

-- профиль создаётся автоматически при регистрации пользователя
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, name, phone)
  values (new.id,
          new.raw_user_meta_data->>'name',
          new.raw_user_meta_data->>'phone');
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- проверка «является ли текущий пользователь админом»
-- (security definer — читает profiles в обход RLS, без рекурсии)
create or replace function public.is_admin()
returns boolean language sql security definer set search_path = public stable as $$
  select exists(
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- ---------- 2. ТОВАРЫ ----------
create table if not exists public.products (
  id         bigint generated by default as identity primary key,
  name       text not null,
  brand      text default '',
  cat        text,                 -- Женское / Мужское / Аксессуары
  type       text,                 -- coat / shirt / ... или свой тип
  price      numeric not null default 0,
  old_price  numeric default 0,
  material   text default '',
  care       text default '',
  descr      text default '',
  tag        text,                 -- Новинка / Sale / своя метка
  sizes      jsonb not null default '[]'::jsonb,
  colors     jsonb not null default '[]'::jsonb,
  images     jsonb not null default '[]'::jsonb,  -- ссылки на фото в Storage
  stock      int  not null default 0,
  delivery   text default '1–3 дня по России',
  created_at timestamptz not null default now()
);

-- ---------- 3. ЗАКАЗЫ ----------
create table if not exists public.orders (
  id         text primary key,      -- например AR-123456
  user_id    uuid references auth.users(id) on delete set null,
  customer   jsonb not null,        -- {name, phone, email}
  delivery   jsonb not null,        -- {method, city, address, pvz, comment}
  payment    jsonb not null,        -- {method, card}
  items      jsonb not null,        -- [{id,name,brand,size,qty,price}]
  subtotal   numeric not null,
  shipping   numeric not null,
  total      numeric not null,
  status     text not null default 'Обработка',
  created_at timestamptz not null default now()
);

-- при создании заказа автоматически уменьшаем остатки товара
create or replace function public.decrement_stock()
returns trigger language plpgsql security definer set search_path = public as $$
declare it jsonb;
begin
  for it in select jsonb_array_elements(new.items) loop
    update public.products
      set stock = greatest(0, stock - coalesce((it->>'qty')::int, 0))
      where id = (it->>'id')::bigint;
  end loop;
  return new;
end; $$;

drop trigger if exists on_order_created on public.orders;
create trigger on_order_created
  after insert on public.orders
  for each row execute procedure public.decrement_stock();

-- ---------- 4. НАСТРОЙКИ САЙТА (одна строка) ----------
create table if not exists public.settings (
  id   int primary key default 1,
  data jsonb not null default '{}'::jsonb,
  constraint settings_single check (id = 1)
);
insert into public.settings (id, data) values (1, '{}'::jsonb)
  on conflict (id) do nothing;

-- ============================================================
--  ЗАЩИТА ДОСТУПА (Row Level Security)
-- ============================================================
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders   enable row level security;
alter table public.settings enable row level security;

-- ПРОФИЛИ: свой профиль видит и меняет сам пользователь; админ видит все
drop policy if exists "profiles select" on public.profiles;
create policy "profiles select" on public.profiles
  for select using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles update" on public.profiles;
create policy "profiles update" on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());

-- ТОВАРЫ: читают все (даже гости); меняет только админ
drop policy if exists "products read" on public.products;
create policy "products read" on public.products
  for select using (true);

drop policy if exists "products admin" on public.products;
create policy "products admin" on public.products
  for all using (public.is_admin()) with check (public.is_admin());

-- ЗАКАЗЫ: создать может любой (в т.ч. гость); видит свои или админ;
--         статус меняет только админ
drop policy if exists "orders insert" on public.orders;
create policy "orders insert" on public.orders
  for insert with check (true);

drop policy if exists "orders select" on public.orders;
create policy "orders select" on public.orders
  for select using (user_id = auth.uid() or public.is_admin());

drop policy if exists "orders admin update" on public.orders;
create policy "orders admin update" on public.orders
  for update using (public.is_admin()) with check (public.is_admin());

-- НАСТРОЙКИ: читают все; меняет админ
drop policy if exists "settings read" on public.settings;
create policy "settings read" on public.settings
  for select using (true);

drop policy if exists "settings admin" on public.settings;
create policy "settings admin" on public.settings
  for update using (public.is_admin()) with check (public.is_admin());

-- ============================================================
--  ГОТОВО. Дальше — назначить себя админом (см. инструкцию, Часть 1,
--  шаг 6): update public.profiles set role='admin' where id='ВАШ_UUID';
-- ============================================================
